<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Skip</name>
   <tag></tag>
   <elementGuidId>8163726e-a8bf-4019-ba46-641c4cdf4c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GLUXProgramSpecificSheetSkipLink > a.a-link-normal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='GLUXProgramSpecificSheetSkipLink']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0ab2537-221e-4750-abc9-b76189362f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>e834d650-497c-45f2-a386-9d23ba8ca54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>05d7aa73-a85a-48f6-bdc9-c07b714bc941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXProgramSpecificSheetSkipLink&quot;)/a[@class=&quot;a-link-normal&quot;]</value>
      <webElementGuid>c38b90a1-af3c-467c-ab4a-0dec2dbbec59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GLUXProgramSpecificSheetSkipLink']/a</value>
      <webElementGuid>f2c4ef1b-779c-4ce7-a5be-eb1fd5e835bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Skip')])[2]</value>
      <webElementGuid>8bf6154c-178c-4397-81b1-dcdbd35c3ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>42410aa0-bb67-4932-b758-956df7abc33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>7957e43a-9265-4a3f-96a4-8c396aad849b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
