<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_amazon.in</name>
   <tag></tag>
   <elementGuidId>eab12ee3-bf94-4a4b-aa4d-a0a940b04ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.OSrXXb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tads']/div/div/div/div/div/a/div[2]/span/span[2]/span/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3123b188-7827-4297-b23d-40fd8fc5183d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSrXXb</value>
      <webElementGuid>a9dbf574-9b65-43ab-86a5-d84f7c858026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>amazon.in</value>
      <webElementGuid>dde44e2c-2aec-4cc0-b11c-b903252c13f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tads&quot;)/div[@class=&quot;uEierd&quot;]/div[1]/div[1]/div[@class=&quot;vdQmEd fP1Qef xpd EtOod pkphOe&quot;]/div[@class=&quot;v5yQqb&quot;]/a[@class=&quot;sVXRqc&quot;]/div[@class=&quot;d8lRkd&quot;]/span[@class=&quot;yIn8Od&quot;]/span[@class=&quot;wbJOMb&quot;]/span[@class=&quot;pKWwCd yUTMj&quot;]/div[@class=&quot;Aozhyc Va3FIb TElO2c OSrXXb&quot;]/span[@class=&quot;OSrXXb&quot;]</value>
      <webElementGuid>041d5531-5ad3-4f65-a770-52cd920d873c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tads']/div/div/div/div/div/a/div[2]/span/span[2]/span/div/span</value>
      <webElementGuid>0f34c1bc-1bb2-46e7-8ffd-8b939399de48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span/div/span</value>
      <webElementGuid>6ab86246-c81f-4ea8-b974-a523e42b7abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'amazon.in' or . = 'amazon.in')]</value>
      <webElementGuid>15620be9-774c-40a5-8063-d4bb3371d38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
