<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product-image</name>
   <tag></tag>
   <elementGuidId>c7407aef-dadc-45d1-b877-a2d0ae700525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dad41c3a-cd83-44ac-bf1b-19e7a762d834']/div[2]/div/ul/li[2]/span/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5fe2782f-c6e5-4e53-a389-65fffd6c6a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bergmann Typhoon Heavy Duty Metal Car Tyre Inflator (Blue)</value>
      <webElementGuid>9315c8e3-83fd-4a50-a9fa-008970ac8911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/818kmzObgCL._AC_SY400_.jpg</value>
      <webElementGuid>a0bf9865-8172-45cb-8952-cd7b9801ff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image</value>
      <webElementGuid>73e8893f-fa02-4f45-b06b-dcf6ace5151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200px</value>
      <webElementGuid>44466663-c199-4330-894a-1dbf3bda651c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/818kmzObgCL._AC_SY400_.jpg</value>
      <webElementGuid>f6d81fe1-f32d-459d-a21c-f1e5f50ac77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dad41c3a-cd83-44ac-bf1b-19e7a762d834&quot;)/div[@class=&quot;a-section a-spacing-none feed-carousel hovering&quot;]/div[@class=&quot;a-section feed-carousel-viewport&quot;]/ul[@class=&quot;a-unordered-list a-nostyle a-horizontal feed-carousel-shelf&quot;]/li[@class=&quot;feed-carousel-card&quot;]/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;a-link-normal&quot;]/img[@class=&quot;product-image&quot;]</value>
      <webElementGuid>2262d2ae-6eae-41c6-8caa-b9ba2534dac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dad41c3a-cd83-44ac-bf1b-19e7a762d834']/div[2]/div/ul/li[2]/span/a/img</value>
      <webElementGuid>530a4b4c-4a96-48f9-93be-c1fc48f2e106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bergmann Typhoon Heavy Duty Metal Car Tyre Inflator (Blue)']</value>
      <webElementGuid>1858e3b0-61aa-4427-89ad-28bf45a7c506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/ul/li[2]/span/a/img</value>
      <webElementGuid>971562ed-fb80-4e77-bdcf-4f59b39b5b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bergmann Typhoon Heavy Duty Metal Car Tyre Inflator (Blue)' and @src = 'https://m.media-amazon.com/images/I/818kmzObgCL._AC_SY400_.jpg']</value>
      <webElementGuid>1fecec31-519b-4a57-96cc-d60ae36adbec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
