<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fresh</name>
   <tag></tag>
   <elementGuidId>4584655d-9be7-4b6c-b1cc-4239f18ec8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-link-groceries</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-link-groceries']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f5369b2-6cba-4e22-a07f-57fa64a5fcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fresh?ref_=nav_cs_grocery</value>
      <webElementGuid>12a2469d-b211-4bf5-bde0-d7ca5770901b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a   nav-active</value>
      <webElementGuid>e06537f3-9102-48b1-9606-cb6adb88177b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ux-jq-mouseenter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac4c1c22-88d6-4a1f-a0f6-650d489c8eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-groceries</value>
      <webElementGuid>79fa5b15-d6fa-49e4-96e5-10f23c385684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fafb806f-0975-4cc6-8ef3-e25e3b233964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>1846dd25-f9c0-433a-a757-3339d7dbaa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav-link-groceries</value>
      <webElementGuid>db68f030-dbf1-4960-85bf-78294ba5a03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_grocery</value>
      <webElementGuid>1be3acf3-d6f2-438c-ad9c-65ade1685649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>a3tf39-obv2ov-1tohed-7zia3f</value>
      <webElementGuid>ded2681b-7cc9-434f-8e1c-1bd168f50516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fresh</value>
      <webElementGuid>3ff7bb47-9ab2-4502-8399-b330e05124be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-groceries&quot;)</value>
      <webElementGuid>2364ce2b-3006-4f6e-a879-520e41fe044e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-link-groceries']</value>
      <webElementGuid>a9f2b902-6080-47f5-965d-e98855e1059d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a</value>
      <webElementGuid>9079cde1-99f9-490c-a141-f87c35b9d31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fresh?ref_=nav_cs_grocery')]</value>
      <webElementGuid>437d979f-2a95-4367-af44-3bbc85cc5c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>4375e5a2-8a1a-40ba-aa22-aeb75847b293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fresh?ref_=nav_cs_grocery' and @id = 'nav-link-groceries' and (text() = 'Fresh' or . = 'Fresh')]</value>
      <webElementGuid>46764a7c-b2f6-4984-abc3-1f444877a3c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
