<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bookSeatconfirmedContinue</name>
   <tag></tag>
   <elementGuidId>4c262f3c-f7d6-41d3-9bce-3116b32a736c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()=&quot;Skip&quot;]/parent::div/parent::div/following-sibling::div//div[text()=&quot;Continue&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
