<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonContinue2</name>
   <tag></tag>
   <elementGuidId>a3e6b01f-b573-4d6a-a121-29363941d2a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[text()=&quot;Continue&quot;]/parent::div[@data-testid=&quot;add-ons-continue-footer-button&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
