<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contactNumber</name>
   <tag></tag>
   <elementGuidId>12602763-74e1-44a9-950c-73e5adb78f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(text(),&quot;Number&quot;)]/parent::div/following-sibling::div/input)[${id}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
