<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popupContinueButton</name>
   <tag></tag>
   <elementGuidId>10a22b8c-70ff-484a-b92d-bd164e7c6dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),&quot;Discount&quot;)]/parent::div/parent::div//div[text()=&quot;Continue&quot;]/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
