<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectFirstMeal</name>
   <tag></tag>
   <elementGuidId>51b893d4-932f-4cdf-b495-2ab32f9fe791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[text()=&quot;VEG&quot;]/parent::div/parent::div/parent::div//img/parent::div/parent::div/parent::div/parent::div)[${id}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
