<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>start_date</name>
   <tag></tag>
   <elementGuidId>514b9802-6e6a-45e2-bf93-946af05ce67c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid=&quot;undefined-month-February-2024&quot;]//div[@data-testid=&quot;undefined-calendar-day-21&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
