<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>more_dropdownOption</name>
   <tag></tag>
   <elementGuidId>87e6ed2d-e1da-40e9-b547-bc92e4ece96a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[contains(@class,&quot;navbar&quot;)]//a[contains(text(),&quot;More&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
